from hank import Commands

# list of commands and the times we need to send them. (seconds : command)
command_times = {
    11: Commands.SIT_DOWN,
    38: Commands.STAND_UP,
    48: Commands.SIT_DOWN,
    54: Commands.STAND_UP,
    67: Commands.SIT_DOWN,
    77: Commands.SIT_DOWN,
    84: Commands.STAND_UP,
    89: Commands.STEP_RIGHT,
    148: Commands.WALK_RIGHT,
    165: Commands.STOP,
    172: Commands.STEP_LEFT,
    179: Commands.STOP,
    185: Commands.STEP_RIGHT,
    191: Commands.STOP,
    205: Commands.WALK_LEFT,
    211: Commands.STOP,
    230: Commands.STEP_LEFT,
    233: Commands.SIT_DOWN,
    242: Commands.STAND_UP,
    254: Commands.SIT_DOWN,
    272: Commands.STAND_UP,
    282: Commands.STOP,
    296: Commands.WALK_LEFT,
    350: Commands.WALK_RIGHT,
    360: Commands.STOP,
    383: Commands.STOP,
    387: Commands.STEP_LEFT,
    396: Commands.STEP_RIGHT,
    401: Commands.STEP_LEFT,
    407: Commands.STEP_RIGHT,
    413: Commands.STEP_LEFT,
    418: Commands.STOP,
    446: Commands.SIT_DOWN,
    453: Commands.STAND_UP,
    458: Commands.STEP_RIGHT,
    464: Commands.STEP_LEFT,
    469: Commands.STEP_RIGHT,
    476: Commands.STEP_LEFT,
    481: Commands.STEP_RIGHT,
    487: Commands.STEP_LEFT,
    494: Commands.STOP,
    497: Commands.STOP,
    513: Commands.WALK_RIGHT,
    550: Commands.WALK_LEFT,
    559: Commands.STOP,
    564: Commands.STAND_UP,
    575: Commands.SIT_DOWN,
    583: Commands.STAND_UP,
    595: Commands.SIT_DOWN
}
